package io.github.sergeiionin

import scala.util.Random

// a small list of the decorous jokes about Chuck Norris from https://api.chucknorris.io/jokes/random,
// https://www.reddit.com/r/ChuckNorrisJokes and generated by Copilot (not sure if they are fully original)
class JokesService:
  private val list =
    List(
      "If Superman and The Flash had a race to the end of the world, Chuck Norris would be the winner.",
      "Chuck Norris can divide by zero.",
      "Chuck Norris can slam a revolving door.",
      "Chuck Norris can unscramble an egg.",
      "Chuck Norris can hear sign language.",
      "Chuck Norris does not use a calendar, he decides which year it is",
      "Chuck Norris can tie his shoes with his feet.",
      "Chuck Norris can speak Braille.",
      "When Alexander Graham Bell invented the phone, he already had 3 missed calls from Chuck Norris. ",
      "Chuck Norris can play the violin on a piano.",
      "Chuck Norris can make a snowman out of rain.",
      "Chuck Norris can make a slinky go upstairs.",
      "Chuck Norris can make a fire by rubbing two ice cubes together.",
      "Chuck Norris can make a tomato turn red.",
      "When Chuck Norris gets a penalty wile playing hockey, the ref go's in the penalty box.",
      "Some people can ride a bike no-handed; Chuck Norris can ride a scooter NO-LEGGED",
      "Chuck Norris REALLY went back to the future.",
      "Google uses Chuck Norris as a search engine."
    )

  val jokesMap: Map[Int, String] =
    val indexes = List.range(0, list.size)
    (indexes zip list).toMap

  def getJoke: String = jokesMap(Random().nextInt(jokesMap.size-1))
